import { useRef, useState } from 'react'
import { format } from 'date-fns'
import type { RosterLayer } from '../../shared/types'
import { useHolidays } from '../api/admin'
import { useRoster } from '../api/rosters'
import { LogoMark, WhatsAppIcon } from '../components/icons'
import { Button, Card, MiniLabel, PenDot } from '../components/ui'
import { addMonths, dayOfWeek, monthGridRows, monthLabel, todayMonth } from '../lib/dates'
import { exportRosterImage } from '../lib/share'
import { useUnitId } from '../lib/useUnitId'

const WEEKDAYS = ['MON', 'TUE', 'WED', 'THU', 'FRI', 'SAT', 'SUN']

export default function SharePage() {
  const unitId = useUnitId()
  const [layer, setLayer] = useState<RosterLayer>('SHO')
  const [month, setMonth] = useState(todayMonth())
  const { data } = useRoster(unitId, layer, month)
  const { data: holidayList = [] } = useHolidays(month)
  const holidays = Object.fromEntries(holidayList.map((h) => [h.date.slice(0, 10), h.name]))
  const roster = data?.roster ?? null
  const exportRef = useRef<HTMLDivElement>(null)
  const [sharing, setSharing] = useState(false)

  const byDate = new Map((roster?.slots ?? []).map((s) => [s.date.slice(0, 10), s]))
  const title = `${monthLabel(month)} — ${layer === 'SHO' ? 'SHO/RHO on-call' : 'Consultant casualty'}`
  const footer = roster
    ? `GENERATED BY MEDIROSTER · V${roster.version}${
        roster.publishedAt
          ? ` · PUBLISHED ${format(new Date(roster.publishedAt), 'MMM d, HH:mm').toUpperCase()}`
          : ' · DRAFT'
      }`
    : ''

  const legend = [...new Map((roster?.slots ?? []).map((s) => [s.staffId, s.staff])).values()]

  const doExport = async () => {
    if (!exportRef.current) return
    setSharing(true)
    try {
      await exportRosterImage(exportRef.current, `mediroster-${layer.toLowerCase()}-${month}.png`)
    } finally {
      setSharing(false)
    }
  }

  return (
    <div className="mx-auto max-w-[1040px] px-4 py-6 md:px-7 md:py-[30px]">
      <div className="print:hidden">
        <MiniLabel>Share & export · how rosters actually circulate</MiniLabel>
        <h1 className="mt-1.5 font-display text-[28px] leading-[1.1] font-semibold tracking-tight md:text-4xl">
          One tap to the WhatsApp group
        </h1>
        <div className="mt-1.5 font-mono text-xs text-ink-2 uppercase">
          PNG sized for WhatsApp compression · print fits A4 landscape for the notice board
        </div>
      </div>

      <div className="mt-6 flex flex-col items-start gap-[22px] lg:flex-row">
        {/* ── Export artifact ── */}
        <div className="min-w-0 flex-1">
          <div className="mb-3 flex flex-wrap items-center gap-2 print:hidden">
            <div className="flex gap-0.5 rounded-md border border-grid bg-surface p-[3px]">
              {(['SHO', 'CONSULTANT'] as const).map((l) => (
                <button
                  key={l}
                  onClick={() => setLayer(l)}
                  className={`h-[30px] rounded px-3 text-[13px] transition-colors ${
                    layer === l
                      ? 'bg-teal-50 font-semibold text-ink'
                      : 'font-medium text-ink-2 hover:bg-sunken'
                  }`}
                >
                  {l === 'SHO' ? 'SHO/RHO' : 'Consultant'}
                </button>
              ))}
            </div>
            <div className="flex gap-0.5 rounded-md border border-grid bg-surface p-[3px]">
              {[addMonths(month, -1), month, addMonths(month, 1)].map((m) => (
                <button
                  key={m}
                  onClick={() => setMonth(m)}
                  className={`h-[30px] rounded px-3 text-[13px] transition-colors ${
                    m === month
                      ? 'bg-teal-50 font-semibold text-ink'
                      : 'font-medium text-ink-2 hover:bg-sunken'
                  }`}
                >
                  {monthLabel(m).slice(0, 3)}
                </button>
              ))}
            </div>
            <span className="text-[11.5px] text-ink-3">
              This is exactly what the exported image looks like.
            </span>
          </div>

          {!roster ? (
            <Card className="px-8 py-16 text-center text-sm text-ink-2">
              No {layer === 'SHO' ? 'SHO/RHO' : 'consultant'} roster for {monthLabel(month)} yet.
            </Card>
          ) : (
            <div
              ref={exportRef}
              className="overflow-hidden rounded-lg border border-grid bg-white shadow-(--shadow-sm)"
            >
              {/* title bar */}
              <div className="flex items-center gap-2.5 border-b-2 border-b-ink px-4 py-3">
                <LogoMark size={20} />
                <span className="font-display text-[17px] font-semibold">{title}</span>
                <span className="flex-1" />
                <span className="hidden font-mono text-[11px] text-ink-2 sm:inline">
                  LRH · PAEDIATRICS · PROF UNIT
                </span>
              </div>
              {/* compact grid */}
              <div className="grid grid-cols-7 border-b border-grid">
                {WEEKDAYS.map((d, i) => (
                  <div
                    key={d}
                    className={`border-r border-grid px-2 py-1.5 text-[10px] font-semibold tracking-[0.04em] last:border-r-0 ${
                      i >= 5 ? 'bg-weekend-bg text-ink-2' : 'text-ink-3'
                    }`}
                  >
                    {d}
                  </div>
                ))}
              </div>
              {monthGridRows(month).map((row, i) => (
                <div key={i} className="grid grid-cols-7">
                  {row.map((date, j) => {
                    if (!date)
                      return (
                        <div
                          key={`p${i}-${j}`}
                          className="min-h-[58px] border-r border-b border-grid bg-sunken last:border-r-0"
                        />
                      )
                    const slot = byDate.get(date)
                    const wk = dayOfWeek(date) === 0 || dayOfWeek(date) === 6
                    const hol = holidays[date]
                    const flag = hol
                      ? { text: 'PH', cls: 'text-danger' }
                      : slot?.isCash
                        ? { text: '◆', cls: 'text-cash' }
                        : slot?.isPostCash
                          ? { text: '■', cls: 'text-postcash' }
                          : slot?.isWeekendBlock
                            ? { text: '48H', cls: 'text-ink-3' }
                            : null
                    return (
                      <div
                        key={date}
                        className={`flex min-h-[58px] flex-col border-r border-b border-grid p-1.5 last:border-r-0 ${
                          hol ? 'bg-holiday-bg' : wk ? 'bg-weekend-bg' : 'bg-white'
                        }`}
                      >
                        <div className="flex items-center justify-between">
                          <span className="font-mono text-[10.5px] text-ink-3">
                            {date.slice(8)}
                          </span>
                          {flag && (
                            <span className={`text-[9.5px] font-bold ${flag.cls}`}>
                              {flag.text}
                            </span>
                          )}
                        </div>
                        <div className="flex flex-1 items-center justify-center">
                          {slot && (
                            <span
                              className="inline-flex h-[22px] min-w-[26px] items-center justify-center rounded-md px-1.5 text-[12.5px] font-semibold"
                              style={{
                                color: `var(--color-${slot.staff.colorKey})`,
                                backgroundColor: `var(--color-${slot.staff.colorKey}-bg)`,
                              }}
                            >
                              {slot.staff.shortCode}
                            </span>
                          )}
                        </div>
                      </div>
                    )
                  })}
                </div>
              ))}
              {/* legend + footer */}
              <div className="flex flex-wrap items-center gap-x-3 gap-y-1 border-t-2 border-t-ink px-4 py-2.5">
                {legend.map((s) => (
                  <span key={s.id} className="inline-flex items-center gap-1.5 text-[11px]">
                    <PenDot colorKey={s.colorKey} className="h-2! w-2!" />
                    <strong className="font-semibold">{s.shortCode}</strong> {s.fullName}
                  </span>
                ))}
                <span className="flex-1" />
                <span className="font-mono text-[10px] text-ink-3">{footer}</span>
              </div>
            </div>
          )}
        </div>

        {/* ── Send it + WhatsApp preview ── */}
        <div className="flex w-full shrink-0 flex-col gap-3.5 lg:w-[300px] print:hidden">
          <Card className="p-4">
            <MiniLabel className="text-ink-3!">Send it</MiniLabel>
            <button
              disabled={!roster || sharing}
              onClick={doExport}
              className="mt-3 flex h-10 w-full items-center justify-center gap-2 rounded-md bg-teal-600 text-sm font-semibold text-white transition-colors hover:bg-teal-700 disabled:opacity-60"
            >
              <WhatsAppIcon />
              {sharing ? 'Rendering…' : 'Share to WhatsApp'}
            </button>
            <Button
              variant="outline"
              className="mt-2 w-full"
              disabled={!roster || sharing}
              onClick={doExport}
            >
              Download PNG
            </Button>
            <Button
              variant="ghost"
              className="mt-2 w-full"
              disabled={!roster}
              onClick={() => window.print()}
            >
              Print · A4 landscape
            </Button>
            <p className="mt-3 text-[11.5px] leading-normal text-ink-2">
              Exports always carry the month, version and publish time so the group can spot
              stale copies.
            </p>
          </Card>

          <Card className="p-4">
            <MiniLabel className="text-ink-3!">How it lands in the group</MiniLabel>
            <div className="mt-[11px] rounded-lg bg-sunken p-3">
              <div className="mb-2 text-[11px] font-semibold text-ink-2">
                Pead Prof Unit · 14 members
              </div>
              <div className="max-w-[230px] rounded-lg border border-grid bg-white p-[7px] shadow-(--shadow-xs)">
                <div className="overflow-hidden rounded-[5px] border border-grid">
                  <div className="flex items-center gap-1.5 border-b border-b-ink px-2 py-1.5">
                    <span className="font-display text-[11px] font-semibold">{title}</span>
                  </div>
                  <div className="grid grid-cols-7">
                    {monthGridRows(month)
                      .flat()
                      .slice(0, 14)
                      .map((date, i) => {
                        const slot = date ? byDate.get(date) : null
                        return (
                          <span
                            key={i}
                            className="h-[13px] border-r border-b border-grid"
                            style={{
                              backgroundColor: slot
                                ? `var(--color-${slot.staff.colorKey}-bg)`
                                : 'var(--color-sunken)',
                            }}
                          />
                        )
                      })}
                  </div>
                </div>
                <p className="mt-[7px] text-[11px] leading-snug">
                  {monthLabel(month)} {layer === 'SHO' ? 'on-call' : 'consultant casualty'} roster
                  — published. Tap to view your days.
                </p>
                <div className="mt-1 text-right font-mono text-[9.5px] text-ink-3">21:18 ✓✓</div>
              </div>
            </div>
          </Card>
        </div>
      </div>
    </div>
  )
}
